exclude: ^.idea/
repos:
-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
    -   id: autoflake
        args: [--in-place, --remove-all-unused-imports, --remove-unused-variable]
-   repo: https://github.com/ambv/black
    rev: 21.5b0
    hooks:
    -   id: black
        language_version: python3.6
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        args: [--strict, --python-version=3.6, --show-error-codes, --allow-untyped-decorators]
        additional_dependencies:
            - numpy>=1.19.2
            - pyspark==3.1.1
            - logger
            - pytest
