version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: spark.Dockerfile
      context: .
    image: sparkfhirschemas_dev
    volumes:
      - ./:/sfs/
    container_name: sparkfhirschemas_dev
    working_dir: /sfs
