#!/bin/bash

GIT_PROJECT_ROOT=$(git rev-parse --show-toplevel)
cd "$($GIT_PROJECT_ROOT "$0")"
docker build -f ./pre-commit.Dockerfile -t pre-commit-sfs . && docker run --rm --name pre-commit-sfs-run -v $(pwd)/:/sourcecode pre-commit-sfs
